service: selenium-lambda

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - package*.json
    - .serverless/**
    - serverless.yml
  include:
    - chromedriver/**

provider:
  name: aws
  runtime: python3.7
  region: us-west-1
  timeout: 900

functions:
  differ:
    handler: handler.differ
    environment:
      PUSHBULLET_ACCESS_TOKEN: ${env:PUSHBULLET_ACCESS_TOKEN}
      PUSHBULLET_DEVICE_IDEN: ${env:PUSHBULLET_DEVICE_IDEN}
    events: ${file(./config.yml):events}
