on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - name: serverless deploy
      uses: dschep/serverless-python-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IFTTT_EVENT: ${{ secrets.IFTTT_EVENT }}
        IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
    - name: serverless invoke
      uses: dschep/serverless-python-action@master
      with:
        args: invoke -f differ
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
